name: security

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, reopened, synchronize]

jobs: 
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: mdegis/bandit-action@v1.1
